version: '3'

services:

  api:
    environment:
      - CODECHAT_BASE_URL=http://codechat:${CODECHAT_PORT:-8083}
    links:
      - codechat
    depends_on:
      - codechat

  codechat:
    image: codechat/api:latest
    restart: always
    ports:
      - ${CODECHAT_PORT:-8083}:8083
    volumes:
      - ./.data/instances:/codechat/instances
    environment:
      - AUTHENTICATION_API_KEY=${CODECHAT_API_KEY:-t8OOEeISKzpmc3jjcMqBWYSaJsafdefer}
      - WEBHOOK_GLOBAL_ENABLED=true
      - WEBHOOK_GLOBAL_URL=http://api:${PORT-1234}
      - DATABASE_ENABLED=false
      - REDIS_ENABLED=false
    command: ['node', '--trace-warnings', './dist/src/main.js']
